# Generated by Django 5.1.6 on 2025-03-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ujgamex", "0004_ludoleaderboard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chessleaderboard",
            old_name="user",
            new_name="player",
        ),
        migrations.RenameField(
            model_name="chessleaderboard",
            old_name="final_score",
            new_name="score",
        ),
        migrations.RemoveField(
            model_name="chessleaderboard",
            name="draws",
        ),
        migrations.DeleteModel(
            name="LudoLeaderboard",
        ),
    ]
