# Generated by Django 5.1.6 on 2025-03-17 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ujgamex", "0005_rename_user_chessleaderboard_player_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LudoMatchLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.CharField(max_length=50)),
                ("score", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="gameleaderboard",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="memoryleaderboard",
            options={"ordering": ["time_taken"]},
        ),
        migrations.RemoveField(
            model_name="memoryleaderboard",
            name="final_score",
        ),
        migrations.RemoveField(
            model_name="memoryleaderboard",
            name="matches_found",
        ),
        migrations.RemoveField(
            model_name="memoryleaderboard",
            name="moves_taken",
        ),
        migrations.RemoveField(
            model_name="snakeleaderboard",
            name="date_played",
        ),
        migrations.AddField(
            model_name="memoryleaderboard",
            name="time_taken",
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name="memoryleaderboard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="rpsleaderboard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="snakeleaderboard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeleaderboard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="ChessLeaderboard",
        ),
        migrations.DeleteModel(
            name="GameLeaderboard",
        ),
    ]
