# Generated by Django 5.1.6 on 2025-02-24 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujgamex', '0006_alter_rockpaperscissorsleaderboard_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rockpaperscissorsleaderboard',
            name='final_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rockpaperscissorsleaderboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
