# Generated by Django 5.1.6 on 2025-02-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujgamex', '0007_rockpaperscissorsleaderboard_final_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPSLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
